#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : potrace
Version  : 1.16
Release  : 6
URL      : https://sourceforge.net/projects/potrace/files/1.16/potrace-1.16.tar.gz
Source0  : https://sourceforge.net/projects/potrace/files/1.16/potrace-1.16.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: potrace-bin = %{version}-%{release}
Requires: potrace-lib = %{version}-%{release}
Requires: potrace-license = %{version}-%{release}
Requires: potrace-man = %{version}-%{release}
BuildRequires : pkgconfig(zlib)

%description
POTRACE - transform bitmaps into vector graphics

* * *

DESCRIPTION
Potrace is a tool for tracing a bitmap, which means, transforming a
bitmap into a smooth, scalable image.  The input is a bitmap (PBM,
PGM, PPM, or BMP), and the output is one of several vector file
formats.  A typical use is to create SVG or PDF files from scanned
data, such as company or university logos, handwritten notes, etc.
The resulting image is not "jaggy" like a bitmap, but smooth. It can
then be rendered at any resolution.

%package bin
Summary: bin components for the potrace package.
Group: Binaries
Requires: potrace-license = %{version}-%{release}

%description bin
bin components for the potrace package.


%package dev
Summary: dev components for the potrace package.
Group: Development
Requires: potrace-lib = %{version}-%{release}
Requires: potrace-bin = %{version}-%{release}
Provides: potrace-devel = %{version}-%{release}
Requires: potrace = %{version}-%{release}

%description dev
dev components for the potrace package.


%package doc
Summary: doc components for the potrace package.
Group: Documentation
Requires: potrace-man = %{version}-%{release}

%description doc
doc components for the potrace package.


%package lib
Summary: lib components for the potrace package.
Group: Libraries
Requires: potrace-license = %{version}-%{release}

%description lib
lib components for the potrace package.


%package license
Summary: license components for the potrace package.
Group: Default

%description license
license components for the potrace package.


%package man
Summary: man components for the potrace package.
Group: Default

%description man
man components for the potrace package.


%prep
%setup -q -n potrace-1.16
cd %{_builddir}/potrace-1.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604875634
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --with-libpotrace
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604875634
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/potrace
cp %{_builddir}/potrace-1.16/COPYING %{buildroot}/usr/share/package-licenses/potrace/442fcd42809b532269b4666c6fe50071e4a6b17e
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mkbitmap
/usr/bin/potrace

%files dev
%defattr(-,root,root,-)
/usr/include/potracelib.h
/usr/lib64/libpotrace.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/potrace/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpotrace.so.0
/usr/lib64/libpotrace.so.0.0.6

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/potrace/442fcd42809b532269b4666c6fe50071e4a6b17e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mkbitmap.1
/usr/share/man/man1/potrace.1
